<?php
//zskj0328
$enumdata=array(
	'shoplevel'=>array(
		array('key'=>'1','txt'=>'低端'),
		array('key'=>'2','txt'=>'中档'),
		array('key'=>'3','txt'=>'高档'),
	),
	'trades'=>array(//行业类别
		array('key'=>'1','txt'=>'公众场所'),
		array('key'=>'2','txt'=>'酒店宾馆'),
		array('key'=>'3','txt'=>'购物商超'),
        array('key'=>'4','txt'=>'政府医疗'),
		array('key'=>'5','txt'=>'车站机场'),
        array('key'=>'6','txt'=>'教育培训'),
        array('key'=>'7','txt'=>'咖啡厅'),
        array('key'=>'8','txt'=>'洗浴足浴'),
        array('key'=>'9','txt'=>'KTV'),
        array('key'=>'10','txt'=>'健身房'),
        array('key'=>'11','txt'=>'美容美体'),
        array('key'=>'12','txt'=>'母婴用品'),
        array('key'=>'13','txt'=>'化妆品'),
        array('key'=>'14','txt'=>'IT数码'),
        array('key'=>'15','txt'=>'美发'),
        array('key'=>'16','txt'=>'图书'),
        array('key'=>'17','txt'=>'礼品'),
        array('key'=>'18','txt'=>'医疗'),
        array('key'=>'19','txt'=>'婚纱摄影'),
        array('key'=>'20','txt'=>'汽车服务'),
        array('key'=>'21','txt'=>'宠物店'),
        array('key'=>'22','txt'=>'台球厅'),
        array('key'=>'23','txt'=>'服装店'),
        array('key'=>'24','txt'=>'广告公司'),
          
                       
        
	),
	'authmode'=>array(
	    array('key'=>'4','txt'=>'微信分享','code'=>'qq'),
	    array('key'=>'3','txt'=>'微信认证','code'=>'wecha'),
		array('key'=>'1','txt'=>'手机认证','code'=>'phone'),
		array('key'=>'2','txt'=>'无需认证','code'=>'allow'),
		array('key'=>'0','txt'=>'注册认证','code'=>'reg'),
		
		
	),
	'route_id'=>array(//主营路由器品牌
	 array('key'=>'sxtg350','txt'=>'广告路由G350'),
	 array('key'=>'sxtg580','txt'=>'广告路由G580'),
		array('key'=>'sxtg720','txt'=>'广告路由G720'),
		array('key'=>'sxtg730','txt'=>'广告路由G730'),
		array('key'=>'sxtg760','txt'=>'广告路由G760'),
		array('key'=>'sxtap335','txt'=>'广告路由AP335'),
		array('key'=>'sxtap550','txt'=>'广告路由AP550'),
		array('key'=>'sxtap610','txt'=>'广告路由AP610'),
		array('key'=>'sxtap360','txt'=>'广告路由AP360'),
		array('key'=>'sxtap315','txt'=>'广告路由AP315'),
		array('key'=>'sxtap325','txt'=>'广告路由AP325'),
		array('key'=>'sxtap650','txt'=>'广告路由AP650'),
		array('key'=>'sxtap696','txt'=>'广告路由AP696'),
		array('key'=>'sxtap100','txt'=>'广告路由AP100'),
		array('key'=>'sxtg589','txt'=>'广告路由G589'),
		array('key'=>'sxtsp168','txt'=>'广告路由SP168'),
		array('key'=>'sxtg780','txt'=>'广告路由G780'),
		 array('key'=>'sxtg840','txt'=>'广告路由G840'),
		array('key'=>'sxt8100','txt'=>'广告路由8100'),	
		array('key'=>'sxt8200','txt'=>'广告路由8200'),
		array('key'=>'sxt8500','txt'=>'广告路由8500'),
        array('key'=>'sxtcpe850','txt'=>'CPEG850'),
        array('key'=>'sxtcpe860','txt'=>'CPEG860'),
        array('key'=>'sxtcpe980','txt'=>'CPEG980'),
         array('key'=>'sxtgac200','txt'=>'网关GAC200'),
        array('key'=>'sxtgac300','txt'=>'网关GAC300'),
         array('key'=>'sxtgac500','txt'=>'网关GAC500'),
    
        array('key'=>'sxtg318','txt'=>'网关G318'),
         array('key'=>'sxtg318','txt'=>'网关G318'),
        array('key'=>'sxtg318','txt'=>'网关G318'),
        array('key'=>'sxtg518','txt'=>'网关G518'),
        array('key'=>'sxtg818','txt'=>'网关G818'),
        array('key'=>'sxtg918','txt'=>'网关G918'),
        
	),
	'manager'=>array(//大区经理
	 array('key'=>'1','txt'=>'孙忠存'),
	 array('key'=>'2','txt'=>'韩冰'),
	 array('key'=>'3','txt'=>'孙豪'),
	)
	
);